fn main() -> Result<(), Box<dyn std::error::Error>> {
    let proto_files = ["src/proto/fileformat.proto", "src/proto/osmformat.proto"];

    for path in &proto_files {
        println!("cargo:rerun-if-changed={path}");
    }

    let out_dir = std::env::var("OUT_DIR")?;

    let file_descriptors = protox::compile(proto_files, ["src/proto/"])?;
    let mut config = prost_build::Config::new();
    config.bytes(["."]);
    config.out_dir(&out_dir);
    config.compile_fds(file_descriptors)?;

    // Both proto files share `package OSMPBF;` so prost produces a single file.
    // Include it directly at the proto module level (flat namespace).
    std::fs::write(
        format!("{out_dir}/mod.rs"),
        "// Generated by prost + protox\ninclude!(\"osmpbf.rs\");\n",
    )?;

    Ok(())
}
